//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebEngine.Web.Tests.StatisticsServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StatisticsServices.IStatisticsService")]
    public interface IStatisticsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatisticsService/UpdateStatistics", ReplyAction="http://tempuri.org/IStatisticsService/UpdateStatisticsResponse")]
        bool UpdateStatistics(System.Nullable<System.DateTime> date, System.Nullable<double> score);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatisticsService/UpdateStatistics", ReplyAction="http://tempuri.org/IStatisticsService/UpdateStatisticsResponse")]
        System.Threading.Tasks.Task<bool> UpdateStatisticsAsync(System.Nullable<System.DateTime> date, System.Nullable<double> score);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatisticsService/GetStatistics", ReplyAction="http://tempuri.org/IStatisticsService/GetStatisticsResponse")]
        TestWebEngine.Web.Extentions.StatisticsServices.StatisticsType GetStatistics();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatisticsService/GetStatistics", ReplyAction="http://tempuri.org/IStatisticsService/GetStatisticsResponse")]
        System.Threading.Tasks.Task<TestWebEngine.Web.Extentions.StatisticsServices.StatisticsType> GetStatisticsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStatisticsServiceChannel : TestWebEngine.Web.Tests.StatisticsServices.IStatisticsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StatisticsServiceClient : System.ServiceModel.ClientBase<TestWebEngine.Web.Tests.StatisticsServices.IStatisticsService>, TestWebEngine.Web.Tests.StatisticsServices.IStatisticsService {
        
        public StatisticsServiceClient() {
        }
        
        public StatisticsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StatisticsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatisticsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatisticsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool UpdateStatistics(System.Nullable<System.DateTime> date, System.Nullable<double> score) {
            return base.Channel.UpdateStatistics(date, score);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateStatisticsAsync(System.Nullable<System.DateTime> date, System.Nullable<double> score) {
            return base.Channel.UpdateStatisticsAsync(date, score);
        }
        
        public TestWebEngine.Web.Extentions.StatisticsServices.StatisticsType GetStatistics() {
            return base.Channel.GetStatistics();
        }
        
        public System.Threading.Tasks.Task<TestWebEngine.Web.Extentions.StatisticsServices.StatisticsType> GetStatisticsAsync() {
            return base.Channel.GetStatisticsAsync();
        }
    }
}
